### PR TITLE
Target Java 10, fix compile, move java8 to core. Fix #355, #358

### LINKED ISSUE #355: Add current JDK to Travis build (allowed failure?)
https://www.deps.co/guides/travis-ci-latest-java/

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by jbgi** [comment]
so neither jdk10, 11 or 12 are able to build the project for now. Weird jdk bugs...

File: core/src/main/java/fj/data/TreeZipper.java [hunk 1]
```diff
@@ -627,6 +627,9 @@ else for (final TreeZipper<A> loc : parent())
             }, f.f(this));
   }
 
+  /**
+   * @param <A>
```
Comment (gliptak) [inline core/src/main/java/fj/data/TreeZipper.java]: This might be triggering the Javadoc fail
```
javadoc: error - An internal exception has occurred. 
	(com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /home/travis/build/functionaljava/functionaljava/core/build/libs/functionaljava-5.0-SNAPSHOT.jar(/fj/data/TreeZipper$2.class)
  undeclared type variable: A
```

Comment (jbgi) [reply core/src/main/java/fj/data/TreeZipper.java]: ah I added that in hope to fix the issue. But that did not solve it. Will remove.

**Comment by jbgi** [comment]
Solved [jdk10 bug](https://bugs.openjdk.java.net/browse/JDK-8187422) by refactoring some anonymous classes as private static classes.
Made JDK11+ optional for now. Did not investigate the cryptic error.

**Comment by gliptak** [comment]
Should we consider submitting a JDK11 bug report?

**Comment by jbgi** [comment]
> Should we consider submitting a JDK11 bug report?

Yes but we should try to minimize the issue first. Appear to come from a class of the quickcheck module. Probably one of the classes responsible from launching the tests, dealing with threads and annotations.

**Comment by jbgi** [comment]
I workaround the last issue under JDK11+. Opened a jdk bug with a "minimal" test case (https://github.com/jbgi/jdk11-big-integer-substract-bug).

The question is, should we merge this in master or in a `5.x` branch?

**Comment by gliptak** [comment]
would ```master``` targeting a 5.0 release (soon) work?

**Comment by jbgi** [comment]
I'd expect the cleanup necessary for a 5.0 release to take a few months, and, at the very least, we have to wait for jdk11 release as it would make sense to target it as it's going to be an LTS version (people are going to switch directly from jdk8 to jdk11).
So it's probably best to create a `series/5.x` branch for now. I will do some cleanup and then (if jdk 11 is released) we would switch the default branch to  `series/5.x`.
To be consistent we should probably also rename current master to  `series/4.x`.
how does that sounds?

**Comment by gliptak** [comment]
I didn't realize that there is still a significant cleanup effort. And good point on the expected JDK transition. Above approach sounds good.

**Comment by jbgi** [comment]
> I didn't realize that there is still a significant cleanup effort. 

Maybe not, but I'd like to also take the opportunity to explore new ideas, like deriving some stuff via derive4j.

@gliptak also could you give me owner rights, so that I can setup default branches correctly?

**Comment by gliptak** [comment]
@jbgi changed your role to Owner
